version: "3.8"

services:
  web:
    build: .
    container_name: dreams-n-prints
    ports:
      - "80:80"
    volumes:
      - .:/usr/local/apache2/htdocs
    restart: always
    networks:
      - dreams-network

networks:
  dreams-network:
    driver: bridge
